spring:
  application:
    name: school_journal
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=school_journal
    username: test
    password: test
server:
  port: 9000